export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO'
export const GET_PROYECTO = 'GET_PROYECTO'
export const ADD_PROYECTO = 'ADD_PROYECTO'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO'
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL'
export const DELETE_PROYECTO = 'DELETE_PROYECTO'

export const TAREAS_PROYECTO = 'TAREAS_PROYECTO'
export const ADD_TAREA = 'ADD_TAREA'
